name: Pandas custom image to DockerHub

on:
  push:
    branches: [main]
    paths:
      - containers/pandas-scibioxl/*
  workflow_dispatch:

env:
  IMAGE: catgumag/pandas-scibioxl

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Get current date (for tag)
        id: getdate
        run: echo ::set-output name=date::$(date +'%Y%m%d')

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./containers/pandas-scibioxl/
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.getdate.outputs.date }}
            ${{ env.IMAGE }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
